/*******************************************************************************
 *
 * Module: Ultra-sonic Sensor
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the Ultra-sonic sensor driver
 *
 * Author: Amr Emad
 *
 *******************************************************************************/

/*******************************************************************************
 *                                  Includes                                   *
 *******************************************************************************/

#include "icu.h"
#include "gpio.h"
#include "std_types.h"
#include "ultrasonic.h"
#include <util/delay.h>	/* To use the delay functions */

/*******************************************************************************
 *                               Global Variables                              *
 *******************************************************************************/

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;

/*******************************************************************************
 *                             Functions Definitions                           *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ICU driver:
 * 1. Setup the ICU call back function.
 * 2. Setup the direction for the trigger pin as output pin through the GPIO diver.
 */
void Ultrasonic_init(void)
{
	/* ICU Configuration */
	const Icu_ConfigType ConfigType = {F_CPU_8,RISING};

	/* Initialize the ICU driver */
	Icu_init(&ConfigType);

	/* Setup the ICU call back function */
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/* Setup the direction for the trigger pin as output pin */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,PIN_OUTPUT);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_LOW);
}

/*
 * Description :
 * Send the trigger pulse to the ultra-sonic sensor.
 */
void Ultrasonic_Trigger(void)
{
	/* Send the trigger pulse to the ultra-sonic sensor */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_LOW);
}

/*
 * Description :
 * Send the trigger pulse by using the Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Utltrasonic_readDistance(void)
{
	uint16 distance = 0;

	/* Send the trigger pulse */
	Ultrasonic_Trigger();

//	distance = (uint16)((float)((uint32)173 * g_timeHigh) / 10000);

	distance = (g_timeHigh / 58) + 1;

	return distance;
}

/*
 * Description :
 * Calculate the high time (pulse time) generated by the ultra-sonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount = 0;
	}
}
