/*******************************************************************************
 *
 * Module: Ultra-sonic Sensor
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the Ultra-sonic sensor driver
 *
 * Author: Amr Emad
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

/*******************************************************************************
 *                                  Includes                                   *
 *******************************************************************************/

#include "std_types.h"
#include "common_macros.h"

/*******************************************************************************
 *                                 Definitions                                 *
 *******************************************************************************/

/* Ultra-sonic Sensor HW Ports and Pins IDs */
#define ULTRASONIC_TRIGGER_PORT_ID		PORTB_ID
#define ULTRASONIC_TRIGGER_PIN_ID		PIN5_ID

#define ULTRASONIC_ECHO_PORT_ID			PORTD_ID
#define ULTRASONIC_ECHO_PIN_ID			PIN6_ID

/*******************************************************************************
 *                             Functions Prototypes                            *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ICU driver:
 * 1. Setup the ICU call back function.
 * 2. Setup the direction for the trigger pin as output pin through the GPIO diver.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Send the trigger pulse to the ultra-sonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * Send the trigger pulse.
 * Start the measurements by the ICU from this moment.
 */
uint16 Utltrasonic_readDistance(void);

/*
 * Description :
 * Calculate the high time (pulse time) generated by the ultra-sonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
